
MYSQL_USERNAME: user
MYSQL_PASSWORD: petitphat1
MYSQL_HOST: localhost
MYSQL_PORT: 3306
MYSQL_DATABASE: docdatabase

#Server config
CONTAINER_PORT: ${PORT}
ACTIVE_PROFILE: dev

#Email config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: marckenlygbeau@gmail.com
EMAIL_PASSWORD: cxmjrheikeieobqv
VERIFY_EMAIL_HOST: http://localhost:3000

JWT_EXPIRATION: 432_000_000
JWT_SECRET: ${SECRET}